name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: typecheck & formatting
        shell: bash
        run: |
          set -xeuo pipefail
          deno cache --unstable mod.ts
          deno fmt --check

      - name: build (macOS)
        shell: bash
        if: matrix.os == 'macos-latest'
        run: |
          mkdir bin
          brew install duckdb
          ./build.sh

      - name: build (linux)
        shell: bash
        if: matrix.os == 'ubuntu-latest'
        run: |
          ./build-linux.sh

      - name: Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release draft"
          draft: true
          files: |
            bin/libduckdb-deno.dylib
            bin/libduckdb-deno.so
